import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import I18nProvider from "@/components/i18nProvider";
import Nav from "@/components/nav/page";
import Button from "@/components/header-button/page";
import MobileHeaderButton from "@/components/header-button/mobile/page";

export const metadata: Metadata = {
  title: "Bishrelt",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
    shortcut: "/favicon.png",
  },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="mn">
      <head>
        <link rel="shortcut icon" href="/favicon.png" />
      </head>

      <body className="font-gip antialiased bg-transparent box-content">
        <I18nProvider>
          <div className="flex min-h-screen relative bg-transparent">

            <div className="hidden md:block">
              <Nav />
            </div>

            <main className="flex-1 relative z-10 overflow-hidden">
              {children}
            </main>

            <div className="absolute top-6 right-6 z-50 hidden md:block">
              <Button />
            </div>

            <div className="absolute top-4 left-0 right-0  flex justify-between items-center md:hidden z-50">
              <MobileHeaderButton />
            </div>

          </div>
        </I18nProvider>
      </body>
    </html>
  );
}
